---
repos:
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.3.2
    hooks:
      - id: checkov_diff
        files: Dockerfile
        args: [--framework, dockerfile]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
